# Generated by Django 5.0.1 on 2025-12-23 15:33

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_update_subscription_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongBPMCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pco_song_id', models.CharField(db_index=True, help_text='Planning Center Online song ID', max_length=50)),
                ('pco_arrangement_id', models.CharField(blank=True, help_text='PCO arrangement ID (if BPM is arrangement-specific)', max_length=50, null=True)),
                ('song_title', models.CharField(help_text='Song title for display and API lookups', max_length=255)),
                ('song_artist', models.CharField(blank=True, help_text='Song artist/author for API lookups', max_length=255)),
                ('bpm', models.PositiveIntegerField(help_text='Beats per minute (tempo)')),
                ('bpm_source', models.CharField(choices=[('pco', 'Planning Center'), ('chord_chart', 'Chord Chart Text'), ('audio_analysis', 'Audio Analysis'), ('songbpm_api', 'SongBPM API'), ('manual', 'Manual Entry')], db_index=True, help_text='Source where BPM was obtained', max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', help_text='Confidence level of the BPM value', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from the BPM source')),
            ],
            options={
                'verbose_name': 'Song BPM Cache',
                'verbose_name_plural': 'Song BPM Caches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='reportcache',
            new_name='core_report_report__bc3997_idx',
            old_name='core_report_report__3e8f61_idx',
        ),
        migrations.RenameIndex(
            model_name='volunteer',
            new_name='core_volunt_organiz_86a3d4_idx',
            old_name='core_volunt_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='volunteerinsight',
            new_name='core_volunt_status_b8ee80_idx',
            old_name='core_volunt_status_7c5e48_idx',
        ),
        migrations.RenameIndex(
            model_name='volunteerinsight',
            new_name='core_volunt_insight_a32652_idx',
            old_name='core_volunt_insight_d8e9e2_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='api_key',
            field=models.CharField(default=core.models.generate_api_key, help_text='API key for external integrations', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='planning_center_app_id',
            field=models.CharField(blank=True, help_text='Planning Center App ID for this organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='planning_center_secret',
            field=models.CharField(blank=True, help_text='Planning Center Secret (encrypted at rest)', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text="URL-friendly identifier (e.g., 'cherry-hills')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='America/Denver', help_text='Organization timezone for scheduling', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='token',
            field=models.CharField(default=core.models.generate_invitation_token, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='team',
            field=models.CharField(blank=True, help_text="Team within the organization (e.g., 'vocals', 'band')", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='volunteer',
            unique_together={('organization', 'planning_center_id')},
        ),
        migrations.AddField(
            model_name='songbpmcache',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_bpm_caches', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='songbpmcache',
            index=models.Index(fields=['pco_song_id', 'organization'], name='core_songbp_pco_son_f9e429_idx'),
        ),
        migrations.AddIndex(
            model_name='songbpmcache',
            index=models.Index(fields=['song_title', 'song_artist'], name='core_songbp_song_ti_a53c67_idx'),
        ),
        migrations.AddConstraint(
            model_name='songbpmcache',
            constraint=models.UniqueConstraint(fields=('organization', 'pco_song_id', 'pco_arrangement_id'), name='unique_org_song_arrangement_bpm'),
        ),
    ]
