# Generated by Django 5.0.1 on 2025-12-24 01:44

from django.db import migrations


def fix_missing_organizations(apps, schema_editor):
    """
    Fix records that were created without an organization.
    Assigns them to the first organization (Cherry Hills).
    """
    Organization = apps.get_model('core', 'Organization')
    Volunteer = apps.get_model('core', 'Volunteer')
    Interaction = apps.get_model('core', 'Interaction')
    ChatMessage = apps.get_model('core', 'ChatMessage')
    FollowUp = apps.get_model('core', 'FollowUp')
    ExtractedKnowledge = apps.get_model('core', 'ExtractedKnowledge')
    VolunteerInsight = apps.get_model('core', 'VolunteerInsight')

    # Get the first organization (Cherry Hills)
    org = Organization.objects.first()
    if not org:
        print("No organization found - skipping migration")
        return

    # Fix Volunteers
    volunteer_count = Volunteer.objects.filter(organization__isnull=True).update(organization=org)
    if volunteer_count:
        print(f"Fixed {volunteer_count} volunteers missing organization")

    # Fix Interactions
    interaction_count = Interaction.objects.filter(organization__isnull=True).update(organization=org)
    if interaction_count:
        print(f"Fixed {interaction_count} interactions missing organization")

    # Fix ChatMessages
    chat_count = ChatMessage.objects.filter(organization__isnull=True).update(organization=org)
    if chat_count:
        print(f"Fixed {chat_count} chat messages missing organization")

    # Fix FollowUps
    followup_count = FollowUp.objects.filter(organization__isnull=True).update(organization=org)
    if followup_count:
        print(f"Fixed {followup_count} follow-ups missing organization")

    # Fix ExtractedKnowledge
    knowledge_count = ExtractedKnowledge.objects.filter(organization__isnull=True).update(organization=org)
    if knowledge_count:
        print(f"Fixed {knowledge_count} extracted knowledge records missing organization")

    # Fix VolunteerInsight (critical for proactive care dashboard)
    insight_count = VolunteerInsight.objects.filter(organization__isnull=True).update(organization=org)
    if insight_count:
        print(f"Fixed {insight_count} volunteer insights missing organization")


def reverse_migration(apps, schema_editor):
    """Reverse is a no-op - we don't want to remove organizations."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_songbpmcache_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_missing_organizations, reverse_migration),
    ]
