# Generated by Django 5.0.1 on 2025-12-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fix_volunteers_missing_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project'),
        ),
        migrations.AlterField(
            model_name='volunteerinsight',
            name='insight_type',
            field=models.CharField(choices=[('engagement_drop', 'Engagement Drop'), ('no_recent_contact', 'No Recent Contact'), ('prayer_need', 'Prayer Need'), ('birthday_upcoming', 'Birthday Upcoming'), ('anniversary_upcoming', 'Anniversary Upcoming'), ('new_volunteer', 'New Volunteer Check-in'), ('returning', 'Returning After Absence'), ('overdue_followup', 'Overdue Follow-up'), ('frequent_declines', 'Frequent Schedule Declines'), ('milestone', 'Service Milestone'), ('interaction_followup', 'Interaction Follow-up Needed')], db_index=True, help_text='Type of care insight', max_length=30),
        ),
    ]
