# Generated by Django 5.0.1 on 2026-02-24 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_documentcategory_document_documentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Plain Text'), ('image', 'Image')], max_length=10),
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='document_images/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('pdf_extract', 'Extracted from PDF'), ('standalone', 'Standalone Upload')], max_length=20)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('embedding_json', models.JSONField(blank=True, null=True)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_images', to='core.organization')),
            ],
            options={
                'ordering': ['document', 'page_number', 'created_at'],
            },
        ),
    ]
