# Generated by Django 5.0.1 on 2026-02-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_nativepushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='nativepushtoken',
            name='unread_badge_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
