# Generated by Django 5.0.1 on 2026-03-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_auditlog_action_messageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday. Used for weekly/biweekly.', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='1-28. Used for monthly/quarterly.', null=True)),
                ('next_due', models.DateField(help_text='Next date to create an instance.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='core.organization')),
                ('source_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule', to='core.project')),
                ('source_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule', to='core.task')),
            ],
            options={
                'ordering': ['next_due'],
            },
        ),
    ]
