# Generated by Django 5.0.1 on 2026-03-19 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_directmessage_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('thumbsup', '👍'), ('thumbsdown', '👎'), ('heart', '❤️'), ('laugh', '😂'), ('exclamation', '❗'), ('question', '❓')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.channelmessage')),
                ('direct_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.directmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('user', 'emoji', 'channel_message'), ('user', 'emoji', 'direct_message')},
            },
        ),
    ]
