# Generated by Django 5.0.1 on 2026-03-23 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_messagereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('query_type', models.CharField(choices=[('chat_query', 'Chat Query'), ('disambiguation', 'Disambiguation'), ('song_selection', 'Song Selection'), ('date_lookup', 'Date Lookup'), ('roster', 'Team Roster'), ('compound_contact', 'Compound Contact'), ('summarization', 'Conversation Summarization'), ('extraction', 'Data Extraction'), ('analytics', 'Analytics'), ('blockout', 'Blockout/Availability'), ('followup', 'Follow-up Creation')], default='chat_query', max_length=30)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('model', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='core_aiusag_organiz_a919f5_idx'), models.Index(fields=['query_type', 'created_at'], name='core_aiusag_query_t_43714e_idx')],
            },
        ),
    ]
