# Generated by Django 5.0.1 on 2026-03-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_aiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64)),
                ('query_text', models.TextField()),
                ('query_type', models.CharField(default='chat_query', max_length=30)),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_caches', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'query_hash'], name='core_airesp_organiz_d74c83_idx')],
                'unique_together': {('organization', 'query_hash')},
            },
        ),
    ]
