# Generated by Django 5.0.1 on 2026-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_task_parent_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='song_submissions',
            field=models.BooleanField(default=True, help_text='Song submission notifications'),
        ),
    ]
