# Generated by Django 5.0.1 on 2026-04-04 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_notificationpreference_song_submissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='decision_marked_at',
            field=models.DateTimeField(blank=True, help_text='When this comment was marked as a decision', null=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='decision_marked_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this comment as a decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='is_decision',
            field=models.BooleanField(default=False, help_text='This comment captures a decision made by the team'),
        ),
    ]
