# Generated by Django 5.0.1 on 2026-04-04 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_conversation_first_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Read State',
                'verbose_name_plural': 'Task Read States',
                'indexes': [models.Index(fields=['user', 'task'], name='core_taskre_user_id_374e0c_idx')],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
