# Generated by Django 5.0.1 on 2026-04-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_taskwatcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='decision_notifications',
            field=models.BooleanField(default=True, help_text="Notify me when a decision is marked in a project I'm in"),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='task_comment_on_assigned',
            field=models.BooleanField(default=True, help_text="Notify me about new comments on tasks I'm assigned to"),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='task_comment_on_watched',
            field=models.BooleanField(default=True, help_text="Notify me about new comments on tasks I'm watching"),
        ),
    ]
