# Generated by Django 5.0.1 on 2026-04-04 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_project_discussions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDiscussionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_decision', models.BooleanField(default=False, help_text='This message captures a decision made by the team')),
                ('decision_marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_messages', to=settings.AUTH_USER_MODEL)),
                ('decision_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_decisions_marked', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.projectdiscussion')),
                ('linked_tasks', models.ManyToManyField(blank=True, related_name='linked_discussion_messages', to='core.task')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='discussion_mentions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.projectdiscussionmessage')),
            ],
            options={
                'verbose_name': 'Discussion Message',
                'verbose_name_plural': 'Discussion Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
