# Generated by Django 5.0.1 on 2026-04-04 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_projectdiscussionmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Visible to all org members (vs private to creator)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='core.organization')),
            ],
            options={
                'verbose_name': 'Project Template',
                'verbose_name_plural': 'Project Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('role_placeholder', models.CharField(blank=True, help_text="Free-text role hint (e.g., 'tech_lead'); not auto-resolved in v1", max_length=100)),
                ('relative_due_offset_days', models.IntegerField(default=0, help_text='Days from event date. Negative = before, positive = after.')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('checklist_items', models.JSONField(blank=True, default=list, help_text='Checklist item titles to create with the task')),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tasks', to='core.projecttemplate')),
            ],
            options={
                'verbose_name': 'Project Template Task',
                'verbose_name_plural': 'Project Template Tasks',
                'ordering': ['order', 'id'],
            },
        ),
    ]
