# Generated by Django 5.0.1 on 2026-04-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_project_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='pco_days_before_service',
            field=models.IntegerField(default=0, help_text='Days before the service date to create the task (0 = same day)'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='pco_service_type_id',
            field=models.CharField(blank=True, default='', help_text="Planning Center service type ID (used when recurrence_type='pco_service')", max_length=50),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='recurrence_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly (same day)'), ('monthly_weekday', 'Monthly (same weekday)'), ('custom', 'Custom Days'), ('pco_service', 'PCO Service (tied to Planning Center services)')], default='weekly', max_length=20),
        ),
    ]
