# Generated by Django 5.0.1 on 2026-04-08 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_tasktemplate_pco_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.FileField(blank=True, upload_to='studio/collections/')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_collections', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_tags', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='CreativePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('lyrics', 'Lyrics'), ('poem', 'Poem'), ('artwork', 'Artwork'), ('audio', 'Audio'), ('video_concept', 'Video Concept'), ('stage_design', 'Stage Design'), ('idea', 'Idea'), ('devotional', 'Devotional'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('media_file', models.FileField(blank=True, upload_to='studio/posts/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('document', 'Document'), ('none', 'None')], default='none', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('is_spotlighted', models.BooleanField(default=False)),
                ('spotlight_note', models.CharField(blank=True, default='', max_length=200)),
                ('embedding_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_posts', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.creativecollection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_posts', to='core.organization')),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='core.creativepost')),
                ('spotlighted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spotlighted_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='core.creativetag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='core_creati_organiz_db87bc_idx'), models.Index(fields=['organization', 'post_type'], name='core_creati_organiz_77a337_idx')],
            },
        ),
    ]
