# Generated by Django 5.0.1 on 2026-04-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_creativecomment_creativereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='studio_builds',
            field=models.BooleanField(default=True, help_text='When someone builds on my post'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='studio_comments',
            field=models.BooleanField(default=True, help_text='Comments on my studio posts'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='studio_new_posts',
            field=models.BooleanField(default=True, help_text='New creative studio posts'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='studio_spotlights',
            field=models.BooleanField(default=True, help_text='When my post is spotlighted'),
        ),
    ]
