# Generated by Django 5.0.1 on 2026-07-10 12:29

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_backfill_trial_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pco_access_token',
            field=core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='pco_auth_method',
            field=models.CharField(blank=True, default='', help_text="How PCO is connected: 'oauth' | 'manual' | ''", max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='pco_refresh_token',
            field=core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='pco_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='planning_center_secret',
            field=core.fields.EncryptedTextField(blank=True, default='', help_text='Planning Center Secret (encrypted at rest)'),
        ),
    ]
