# Generated by Django 5.0.1 on 2025-12-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_default_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Platform administrator with access to all organizations'),
        ),
    ]
