# Generated by Django 5.0.1 on 2025-12-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the onboarding tutorial'),
        ),
    ]
