from django.urls import path
from . import views

urlpatterns = [
    # Public pages
    path('', views.home, name='home'),
    path('pricing/', views.pricing, name='pricing'),
    # Authenticated app
    path('dashboard/', views.dashboard, name='dashboard'),
    path('chat/', views.chat, name='chat'),
    path('chat/send/', views.chat_send, name='chat_send'),
    path('chat/new/', views.chat_new_session, name='chat_new_session'),
    path('chat/feedback/', views.chat_feedback, name='chat_feedback'),
    path('chat/feedback/submit/', views.chat_feedback_submit, name='chat_feedback_submit'),
    # Feedback dashboard
    path('feedback/', views.feedback_dashboard, name='feedback_dashboard'),
    path('feedback/<int:pk>/resolve/', views.feedback_resolve, name='feedback_resolve'),
    path('interactions/', views.interaction_list, name='interaction_list'),
    path('interactions/new/', views.interaction_create, name='interaction_create'),
    path('interactions/<int:pk>/', views.interaction_detail, name='interaction_detail'),
    path('volunteers/', views.volunteer_list, name='volunteer_list'),
    path('volunteers/<int:pk>/', views.volunteer_detail, name='volunteer_detail'),
    # Volunteer matching endpoints (HTMX)
    path('volunteers/match/confirm/', views.volunteer_match_confirm, name='volunteer_match_confirm'),
    path('volunteers/match/create/', views.volunteer_match_create, name='volunteer_match_create'),
    path('volunteers/match/skip/', views.volunteer_match_skip, name='volunteer_match_skip'),
    # Follow-up endpoints
    path('followups/', views.followup_list, name='followup_list'),
    path('followups/<int:pk>/', views.followup_detail, name='followup_detail'),
    path('followups/create/', views.followup_create, name='followup_create'),
    path('followups/<int:pk>/complete/', views.followup_complete, name='followup_complete'),
    path('followups/<int:pk>/update/', views.followup_update, name='followup_update'),
    path('followups/<int:pk>/delete/', views.followup_delete, name='followup_delete'),
    # Analytics and Reporting
    path('analytics/', views.analytics_dashboard, name='analytics_dashboard'),
    path('analytics/engagement/', views.analytics_volunteer_engagement, name='analytics_volunteer_engagement'),
    path('analytics/care/', views.analytics_team_care, name='analytics_team_care'),
    path('analytics/trends/', views.analytics_interaction_trends, name='analytics_interaction_trends'),
    path('analytics/prayer/', views.analytics_prayer_requests, name='analytics_prayer_requests'),
    path('analytics/ai/', views.analytics_ai_performance, name='analytics_ai_performance'),
    path('analytics/export/<str:report_type>/', views.analytics_export, name='analytics_export'),
    path('analytics/refresh/', views.analytics_refresh_cache, name='analytics_refresh_cache'),
    # Proactive Care Dashboard
    path('care/', views.care_dashboard, name='care_dashboard'),
    path('care/dismiss/<int:pk>/', views.care_dismiss_insight, name='care_dismiss_insight'),
    path('care/followup/<int:pk>/', views.care_create_followup, name='care_create_followup'),
    path('care/refresh/', views.care_refresh_insights, name='care_refresh_insights'),
    # Team Communication Hub
    path('comms/', views.comms_hub, name='comms_hub'),
    path('comms/announcements/', views.announcements_list, name='announcements_list'),
    path('comms/announcements/<int:pk>/', views.announcement_detail, name='announcement_detail'),
    path('comms/announcements/<int:pk>/delete/', views.announcement_delete, name='announcement_delete'),
    path('comms/announcements/new/', views.announcement_create, name='announcement_create'),
    path('comms/channels/', views.channel_list, name='channel_list'),
    path('comms/channels/new/', views.channel_create, name='channel_create'),
    path('comms/channels/<slug:slug>/', views.channel_detail, name='channel_detail'),
    path('comms/channels/<slug:slug>/send/', views.channel_send_message, name='channel_send_message'),
    path('comms/channels/message/<int:message_id>/delete/', views.channel_message_delete, name='channel_message_delete'),
    path('comms/messages/', views.dm_list, name='dm_list'),
    path('comms/messages/new/', views.dm_new, name='dm_new'),
    path('comms/messages/<int:user_id>/', views.dm_conversation, name='dm_conversation'),
    path('comms/messages/<int:user_id>/send/', views.dm_send, name='dm_send'),
    path('comms/messages/delete/<int:message_id>/', views.dm_delete, name='dm_delete'),
    # Projects and Tasks
    path('comms/projects/', views.project_list, name='project_list'),
    path('comms/projects/new/', views.project_create, name='project_create'),
    path('comms/projects/<int:pk>/', views.project_detail, name='project_detail'),
    path('comms/projects/<int:pk>/add-member/', views.project_add_member, name='project_add_member'),
    path('comms/projects/<int:pk>/status/', views.project_update_status, name='project_update_status'),
    path('comms/projects/<int:project_pk>/tasks/new/', views.task_create, name='task_create'),
    path('comms/projects/<int:project_pk>/tasks/<int:pk>/', views.task_detail, name='task_detail'),
    path('tasks/<int:pk>/status/', views.task_update_status, name='task_update_status'),
    path('tasks/<int:pk>/assign/', views.task_assign, name='task_assign'),
    path('tasks/<int:pk>/comment/', views.task_comment, name='task_comment'),
    # My Tasks Dashboard
    path('my-tasks/', views.my_tasks, name='my_tasks'),
    # Task Templates (Recurring Tasks)
    path('templates/', views.template_list, name='template_list'),
    path('templates/new/', views.template_create, name='template_create'),
    path('templates/<int:pk>/', views.template_detail, name='template_detail'),
    path('templates/<int:pk>/generate/', views.template_generate, name='template_generate'),
    # Task Checklists
    path('checklists/<int:pk>/toggle/', views.checklist_toggle, name='checklist_toggle'),
    path('tasks/<int:task_pk>/checklists/add/', views.checklist_add, name='checklist_add'),
    path('checklists/<int:pk>/delete/', views.checklist_delete, name='checklist_delete'),
    # Push Notifications
    path('notifications/', views.push_preferences, name='push_preferences'),
    path('notifications/vapid-key/', views.push_vapid_key, name='push_vapid_key'),
    path('notifications/subscribe/', views.push_subscribe, name='push_subscribe'),
    path('notifications/unsubscribe/', views.push_unsubscribe, name='push_unsubscribe'),
    path('notifications/test/', views.push_test, name='push_test'),
    path('notifications/clicked/', views.notification_clicked, name='notification_clicked'),
    path('notifications/device/<int:subscription_id>/remove/', views.push_remove_device, name='push_remove_device'),
    # Subscription & Billing
    path('billing/', views.billing_portal, name='billing_portal'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribe/required/', views.subscription_required, name='subscription_required'),
    path('subscribe/success/', views.subscription_success, name='subscription_success'),
    # Organization Onboarding
    path('signup/', views.onboarding_signup, name='onboarding_signup'),
    path('onboarding/select-plan/', views.onboarding_select_plan, name='onboarding_select_plan'),
    path('onboarding/checkout/', views.onboarding_checkout, name='onboarding_checkout'),
    path('onboarding/checkout/success/', views.onboarding_checkout_success, name='onboarding_checkout_success'),
    path('onboarding/checkout/cancel/', views.onboarding_checkout_cancel, name='onboarding_checkout_cancel'),
    path('onboarding/connect-pco/', views.onboarding_connect_pco, name='onboarding_connect_pco'),
    path('onboarding/invite-team/', views.onboarding_invite_team, name='onboarding_invite_team'),
    path('onboarding/complete/', views.onboarding_complete, name='onboarding_complete'),
    path('invite/<str:token>/', views.accept_invitation, name='accept_invitation'),
    path('webhooks/stripe/', views.stripe_webhook, name='stripe_webhook'),
    # Organization Settings
    path('settings/', views.org_settings, name='org_settings'),
    path('settings/members/', views.org_settings_members, name='org_settings_members'),
    path('settings/members/invite/', views.org_invite_member, name='org_invite_member'),
    path('settings/members/<int:member_id>/role/', views.org_update_member_role, name='org_update_member_role'),
    path('settings/members/<int:member_id>/remove/', views.org_remove_member, name='org_remove_member'),
    path('settings/invitations/<int:invitation_id>/cancel/', views.org_cancel_invitation, name='org_cancel_invitation'),
    path('settings/billing/', views.org_settings_billing, name='org_settings_billing'),
]
