# Generated by Django 5.0.1 on 2026-01-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description for category page (max 160 chars)', max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary shown in listings (max 300 chars)', max_length=300)),
                ('content', models.TextField(help_text='Full post content (supports Markdown)')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title tag (max 60 chars). Leave blank to use post title.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword to optimize for', max_length=100)),
                ('featured_image_url', models.URLField(blank=True, help_text='URL for the featured image (for og:image)')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('author_name', models.CharField(default='Aria Team', help_text='Display name for the author', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('posts', models.ManyToManyField(blank=True, related_name='tags', to='blog.blogpost')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
